"""v1.1.2 feature module; class bodies are kept behavior-compatible."""
from .core import *

class RBS_OT_add_rotation_transfer(bpy.types.Operator):
    bl_idname = "rbs.add_rotation_transfer"
    bl_label = "添加旋转传递"
    bl_options = {"REGISTER", "UNDO"}

    @classmethod
    def poll(cls, context):
        return (
            context.object is not None
            and context.object.type == "ARMATURE"
            and context.object.mode == "POSE"
            and context.active_pose_bone is not None
        )

    def execute(self, context):
        armature = context.object
        active = context.active_pose_bone
        selected = list(context.selected_pose_bones or [])
        pairs = _rotation_transfer_pairs(armature, active, selected)
        if not pairs:
            self.report({"WARNING"}, "请选中活动骨骼及其连续的子骨骼")
            return {"CANCELLED"}

        created = 0
        for owner, source in pairs:
            # Re-adding a chain should replace only this module's generated
            # constraint and leave manually authored Copy Rotation constraints
            # such as the Finger_Inherit setup untouched.
            for old in list(owner.constraints):
                if old.name.startswith(ROTATION_TRANSFER_PREFIX):
                    owner.constraints.remove(old)
            constraint = owner.constraints.new("COPY_ROTATION")
            constraint.name = f"{ROTATION_TRANSFER_PREFIX}{owner.name}"
            constraint.target = armature
            constraint.subtarget = source.name
            constraint.mix_mode = "ADD"
            constraint.owner_space = "LOCAL"
            constraint.target_space = "LOCAL"
            constraint.use_x = True
            constraint.use_y = False
            constraint.use_z = False
            constraint.invert_x = False
            constraint.invert_y = False
            constraint.invert_z = False
            constraint.influence = 1.0
            created += 1

        self.report({"INFO"}, f"已添加 {created} 个旋转传递约束")
        return {"FINISHED"}

class RBS_OT_remove_rotation_transfer(bpy.types.Operator):
    bl_idname = "rbs.remove_rotation_transfer"
    bl_label = "删除旋转传递"
    bl_options = {"REGISTER", "UNDO"}

    @classmethod
    def poll(cls, context):
        return (
            context.object is not None
            and context.object.type == "ARMATURE"
            and context.object.mode == "POSE"
            and context.active_pose_bone is not None
        )

    def execute(self, context):
        armature = context.object
        selected = list(context.selected_pose_bones or [])
        if not selected:
            self.report({"WARNING"}, "请在姿态模式下选择需要删除旋转传递的骨骼")
            return {"CANCELLED"}
        removed = 0
        for pose_bone in selected:
            for constraint in list(pose_bone.constraints):
                if constraint.name.startswith(ROTATION_TRANSFER_PREFIX):
                    pose_bone.constraints.remove(constraint)
                    removed += 1
        if not removed:
            self.report({"WARNING"}, "选中骨骼没有找到旋转传递")
            return {"CANCELLED"}
        self.report({"INFO"}, f"已删除 {removed} 个旋转传递约束")
        return {"FINISHED"}

class RBS_OT_remove_all_rotation_transfer(bpy.types.Operator):
    """Remove every rotation-transfer constraint generated by this add-on."""

    bl_idname = "rbs.remove_all_rotation_transfer"
    bl_label = "删除所有旋转传递"
    bl_options = {"REGISTER", "UNDO"}

    @classmethod
    def poll(cls, context):
        return (
            context.object is not None
            and context.object.type == "ARMATURE"
            and context.object.mode == "POSE"
        )

    def execute(self, context):
        armature = context.object
        removed = 0
        for pose_bone in armature.pose.bones:
            for constraint in list(pose_bone.constraints):
                if constraint.name.startswith(ROTATION_TRANSFER_PREFIX):
                    pose_bone.constraints.remove(constraint)
                    removed += 1
        if not removed:
            self.report({"WARNING"}, "当前骨架没有找到旋转传递")
            return {"CANCELLED"}
        self.report({"INFO"}, f"已删除 {removed} 个旋转传递约束")
        return {"FINISHED"}

